name: Server Tests
on:
  pull_request:
    branches:
      - staging
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      redis-cache:
        image: redis:alpine
        ports:
          - 13000:6379
      redis-queue:
        image: redis:alpine
        ports:
          - 11000:6379
      redis-socketio:
        image: redis:alpine
        ports:
          - 12000:6379
      mariadb:
        image: anandology/mariadb-utf8mb4:10.3
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        check-latest: true
    - name: setup cache for bench
      uses: actions/cache@v2
      with:
        path: ~/bench-cache
        key: ${{ runner.os }}
    - name: install bench
      run: |
        pip3 install frappe-bench
        which bench
    - name: bench init
      run: |
        if [ -d ~/bench-cache/bench.tgz ]
        then
           (cd && tar xzf ~/bench-cache/bench.tgz)
        else
          bench init ~/frappe-bench --skip-redis-config-generation --skip-assets --frappe-branch version-15 --python "$(which python)"
          mysql --host 127.0.0.1 --port 3306 -u root -proot -e "SET GLOBAL character_set_server = 'utf8mb4'"
          mysql --host 127.0.0.1 --port 3306 -u root -proot -e "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'"
          mkdir -p ~/bench-cache
          (cd && tar czf ~/bench-cache/bench.tgz frappe-bench)
        fi
    - name: add apps to bench
      working-directory: /home/runner/frappe-bench
      run: |
        
        # Add additional apps here
        bench get-app erpnext https://github.com/frappe/erpnext --branch version-15
        bench get-app helpdesk https://github.com/frappe/helpdesk --branch main
        bench get-app hrms https://github.com/frappe/hrms --branch version-15
        bench get-app lending https://github.com/frappe/lending --branch version-15
        bench get-app payments https://github.com/frappe/payments --branch version-15
        bench get-app  https://github.com/ONE-F-M/one_fm.git --branch 187567795
    - name: create bench site
      working-directory: /home/runner/frappe-bench
      run: bench new-site --mariadb-root-password root --admin-password admin frappe.test
    - name: install apps
      working-directory: /home/runner/frappe-bench
      run: bench --site frappe.test install-app  erpnext  helpdesk hrms lending payments one_fm
    - name: setup requirements
      working-directory: /home/runner/frappe-bench
      run: bench setup requirements --dev
    - name: allow tests
      working-directory: /home/runner/frappe-bench
      run: bench --site frappe.test set-config allow_tests true
    - name: run tests
      working-directory: /home/runner/frappe-bench
      run: bench --site frappe.test --verbose run-tests --app one_fm  # Test all installed apps
